KfzKonfiguration/KfzKonfiguration/Controllers/ConfigurationController.cs
using KfzKonfiguration.Context;
using KfzKonfiguration.EntityFramework;
using KfzKonfiguration.Helpers;
using KfzKonfiguration.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace KfzKonfiguration.Controllers
{
    public class ConfigurationController : Controller
    {
        // GET: Configuration
        [HttpGet]
        [ActionName("GetAutoById")]
        public ActionResult GetAutoById(string id)
        {

            Auto auto = null;
            using (var entities = new ConfigKfzDBEntities())
            {

                auto = entities.Autos.Include("Getriebes")
                    .Include("Farbes").Include("Felgenes")
                    .Include("Motoleistunges")
                    .Include(" Sonderausstattungenes")
                    .FirstOrDefault(au => au.AutoId.Equals(id, StringComparison.InvariantCultureIgnoreCase));
                if (auto == null)
                {
                    var message = "Not found auto with Id " + id;
                    Log4NetHelper.LogInfo(message);
                    throw new KeyNotFoundException(message);
                }
            }
            return View(auto);
        }

        [HttpGet]
        [ActionName("GetAutos")]
        public JsonResult GetAutos()
        {
            List<Object> listAuto = new List<Object>();

            using (var entities = new ConfigKfzDBEntities())
            {
                listAuto = (from e in entities.Autos
                            select new
                            {
                                Seqid = e.Seqid,
                                AutoName = e.AutoName
                            }).ToList<Object>();
            }

            return Json(listAuto, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        [ActionName("GetElementsByAuto")]
        public JsonResult GetElementsByAuto(int autonumber)//different Autoid
        {
            Dictionary<String, List<Object>> autoElements = new Dictionary<String, List<Object>>();

            List<Object> listFarbe = new List<Object>();
            using (var entities = new ConfigKfzDBEntities())
            {
                listFarbe = (from f in entities.Autos.FirstOrDefault(a => a.Seqid == autonumber).Farbes
                             select new { Seqid = f.Seqid, FarbeName = f.FarbeName }).ToList<Object>();
            }
            return Json(listFarbe, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        [ActionName("GetFarbesByAuto")]
        public JsonResult GetFarbesByAuto(int autonumber)//different Autoid
        {

            Log4NetHelper.LogInfo("choosed Farbe");
            List<Object> listFarbe = new List<Object>();
            using (var entities = new ConfigKfzDBEntities())
            {
                listFarbe = (from f in entities.Autos.FirstOrDefault(a => a.Seqid == autonumber).Farbes
                             select new { Seqid = f.Seqid, FarbeName = f.FarbeName, FarbePrice = f.Price }).ToList<Object>();
            }
            return Json(listFarbe, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        [ActionName("GetGetriebesByAuto")]
        public JsonResult GetGetriebesByAuto(int autonumber)//different Autoid
        {
            List<Object> listGetriebes = new List<Object>();
            using (var entities = new ConfigKfzDBEntities())
            {
                listGetriebes = (from g in entities.Autos.FirstOrDefault(a => a.Seqid == autonumber).Getriebes
                                 select new { Seqid = g.Seqid, GetriebeName = g.GetriebeName, GetriebePrice = g.Price }).ToList<Object>();
            }
            return Json(listGetriebes, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        [ActionName("GetMotoleistungesByAuto")]
        public JsonResult GetMotoleistungesByAuto(int autonumber)//different Autoid
        {
            List<Object> listMotoleistungs = new List<Object>();
            using (var entities = new ConfigKfzDBEntities())
            {
                listMotoleistungs = (from m in entities.Autos.FirstOrDefault(a => a.Seqid == autonumber).Motoleistunges
                                     select new { Seqid = m.Seqid, MotoleistungName = m.MotoleistungName, MotoleistungPrice = m.Price }).ToList<Object>();
            }
            return Json(listMotoleistungs, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        [ActionName("GetFelgenesByAuto")]
        public JsonResult GetFelgenesByAuto(int autonumber)//different Autoid
        {
            List<Object> listFelgenes = new List<Object>();
            using (var entities = new ConfigKfzDBEntities())
            {
                listFelgenes = (from f in entities.Autos.FirstOrDefault(a => a.Seqid == autonumber).Felgenes
                                select new { Seqid = f.Seqid, FelgenName = f.FelgenName, FelgenPrice = f.Price }).ToList<Object>();
            }
            return Json(listFelgenes, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        [ActionName("GetSonderausstattungenesByAuto")]
        public JsonResult GetSonderausstattungenesByAuto(int autonumber)//different Autoid
        {
            List<Object> listSonderausstattungenes = new List<Object>();
            using (var entities = new ConfigKfzDBEntities())
            {
                listSonderausstattungenes = (from s in entities.Autos.FirstOrDefault(a => a.Seqid == autonumber).Sonderausstattungenes
                                             select new { Seqid = s.Seqid, SonderausstattungenName = s.SonderausstattungenName, SonderausstattungenPrice = s.Price }).ToList<Object>();

            }
            return Json(listSonderausstattungenes, JsonRequestBehavior.AllowGet);

        }

        //[Authorize]
        [HttpGet]
        [ActionName("Service")]
        public ActionResult GetService()
        {
            //IList <AutoResponse> auto = null;
            //using (var entities = new ConfigKfzDBEntities())
            //{
            //    auto = entities.Autos.Select(x => new AutoResponse() {
            //        Seqid = x.Seqid,
            //        AutoCode = x.AutoCode,
            //        AutoId = x.AutoId,
            //        AutoName = x.AutoName
            //    }).ToList();
            //}
            return View();
        }

        private void CalculateTotalFee(AutoTicket autoTicket)
        {
            double total = 0.0;
            if (autoTicket.Farbes != null)
            {
                total += autoTicket.Farbes.Price;
            }
            if (autoTicket.Felgenes != null)
            {
                total += autoTicket.Felgenes.Price;
            }
            if (autoTicket.Getriebes != null)
            {
                total += autoTicket.Getriebes.Price;
            }
            if (autoTicket.Motoleistunges != null)
            {
                total += autoTicket.Motoleistunges.Price;
            }
            if (autoTicket.Sonderausstattungenes != null)
            {
                total += autoTicket.Sonderausstattungenes.Sum(x => x.Price);
            }
            autoTicket.TotalPrice = total;
        }
        [HttpGet]
        [ActionName("Ticket")]
        public ActionResult GetTicket(string ticketId)
        {
            AutoTicket autoTicket = null;
            try
            {
                using (var entities = new ConfigKfzDBEntities())
                {
                    var order = entities.Orders.FirstOrDefault(t => t.OrderTicket == ticketId);
                    if (order != null)
                    {
                        var auto = (Auto)Newtonsoft.Json.JsonConvert.DeserializeObject(order.DetailOrder, typeof(Auto));
                        autoTicket = new AutoTicket()
                        {
                            TicketNumber = order.OrderTicket,
                            AutoCode = auto.AutoCode,
                            AutoId = auto.AutoId,
                            AutoName = auto.AutoName,
                            Farbes = auto.Farbes.FirstOrDefault(),
                            Felgenes = auto.Felgenes.FirstOrDefault(),
                            Getriebes = auto.Getriebes.FirstOrDefault(),
                            Motoleistunges = auto.Motoleistunges.FirstOrDefault(),
                            Sonderausstattungenes = auto.Sonderausstattungenes != null ? auto.Sonderausstattungenes.ToList() : null,
                            CreatedDate = order.CreateDate
                        };
                        CalculateTotalFee(autoTicket);
                    }
                }
            }
            catch (Exception ex)
            {
                Log4NetHelper.LogError("Get ticket - " + ticketId + " : " +  ex.Message, ex);
            }
            return View(autoTicket);
        }


        public static String GetTimestamp(DateTime value)
        {
            return value.ToString("yyyyMMddHHmmssffff");
        }
        [HttpPost]
        [ActionName("CreateTicketOrder")]
        public JsonResult CreateTicketOrder(OrderTicketRequest request)
        {

            var urlReviewTicket = string.Empty;
            try
            {
                Order orderTicket = null;
                using (var kfzContext = new ConfigKfzDBEntities())
                {
                   
                    var auto = kfzContext.Autos.First(au => au.Seqid == request.AutoNumber);
                    auto.Farbes = auto.Farbes.Where(f => f.Seqid == request.FaberId).ToList();
                    auto.Getriebes = auto.Getriebes.Where(g => g.Seqid == request.GetriebeId).ToList();
                    auto.Motoleistunges = auto.Motoleistunges.Where(m => m.Seqid == request.MotoleistungId).ToList();
                    auto.Felgenes = auto.Felgenes.Where(m => m.Seqid == request.FelgeneId).ToList();

KfzKonfiguration/KfzKonfiguration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
	<title>@ViewBag.Title - KfzKonfiguration</title>
	@*<link href="http://fonts.googleapis.com/css?family=Titillium+Web:300,400,700|" rel="stylesheet" type="text/css">*@

	@Styles.Render("~/fonts/font-awesome.min.css")
	@Styles.Render("~/Content/css")
	@Styles.Render("~/Content/style.css")

	@RenderSection("styles", required: false)

	@Scripts.Render("~/bundles/modernizr")

	@Scripts.Render("~/bundles/jquery")

	@RenderSection("head_scripts", required: false)


</head>
<body>

	@*<div class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<a href="../" class="navbar-brand">KfzKonfiguration</a>
				<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="navbar-collapse collapse" id="navbar-main">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Home", "Index", "Home")</li>
					<li>@Html.ActionLink("About", "About", "Home")</li>
					<li>@Html.ActionLink("Contact", "Contact", "Home")</li>
					<li>@Html.ActionLink("Service", "Service", "Configuration")</li>
				</ul>

			</div>
		</div>
	</div>*@


	<div id="site-content">
		<header  class="site-header navbar navbar-default">
			@*//navbar-fixed-top style="background-color:black; padding:00px 0px 0px 0px;"*@
			<div class="container">
				<a id="branding" href="../home">
					<img src="../images/logo.png" alt="Company Logo" class="logo" href="../home">
					@*<h1 class="site-title">@Html.ActionLink("KfzKonfiguration", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</h1>*@
					<h1 class="site-title">KfzKonfiguration</h1>
				</a>
				<nav class="main-navigation">
					<button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
					<ul class="menu">
						<li class="menu-item">@Html.ActionLink("Home", "Index", "Home")</li>
						<li class="menu-item">@Html.ActionLink("About", "About", "Home")</li>
						<li class="menu-item">@Html.ActionLink("Contact", "Contact", "Home")</li>
						@*<li class="menu-item current-menu-item"><a href="services.html">Services</a></li>*@
						<li class="menu-item">@Html.ActionLink("Service", "Service", "Configuration")</li>

					</ul>

					@*@Html.Partial("_LoginPartial")*@

				</nav>
				<nav class="mobile-navigation"></nav>
			</div>
		</header> 
	<!-- .site-header -->

		<main class="main-content">

			<div class="fullwidth-block content">
				@*style="padding:200px 0px 0px 0px;"*@
				<div class="container">
					@RenderBody()
				</div>
			</div>

		</main> <!-- .main-content -->

		<footer class="site-footer navbar navbar-default">
			<div class="container">
				<!--
									<div class="subscribe-form">
										<form action="#">
											<input type="text" placeholder="Enter your email to subscribe...">
											<button type="submit"><img src="images/icon-envelope-white.png" alt=""></button>
										</form>
									</div>
				-->
				<div class="social-links">
					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-google-plus"></i></a>
					<a href="#"><i class="fa fa-pinterest"></i></a>
				</div>
				<div class="copy">
					<p>&copy; @DateTime.Now.Year - KfzKonfiguration</p>
				</div>
			</div>
		</footer> <!-- .site-footer -->
	</div> <!-- #site-content -->

	@Scripts.Render("~/bundles/bootstrap")

	<script src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en"></script>

	@Scripts.Render("~/bundles/newapp")

	@RenderSection("scripts", required: false)
	@*scripts section -> Name: scripts neu ktrang con co thi se nhung phan section cua tring con vao doan nay
		khi server tra ve file text html,*@
</body>
</html>